export default [
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":false,
        "internalType":"address",
        "name":"account",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"address",
        "name":"token",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"amount",
        "type":"uint256"
      }
    ],
    "name":"StakeTnd",
    "type":"event"
  },
  {
    "anonymous":false,
    "inputs":[
      {
        "indexed":false,
        "internalType":"address",
        "name":"account",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"address",
        "name":"token",
        "type":"address"
      },
      {
        "indexed":false,
        "internalType":"uint256",
        "name":"amount",
        "type":"uint256"
      }
    ],
    "name":"UnstakeTnd",
    "type":"event"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_sender",
        "type":"address"
      }
    ],
    "name":"acceptTransfer",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address[]",
        "name":"_accounts",
        "type":"address[]"
      }
    ],
    "name":"batchCompoundForAccounts",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address[]",
        "name":"_accounts",
        "type":"address[]"
      },
      {
        "internalType":"uint256[]",
        "name":"_amounts",
        "type":"uint256[]"
      }
    ],
    "name":"batchStakeTndForAccount",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"bnTnd",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"bonusTndTracker",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"claim",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"claimEsTnd",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"claimFees",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"compound",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_account",
        "type":"address"
      }
    ],
    "name":"compoundForAccount",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"esTnd",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"feeTndTracker",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"gov",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"bool",
        "name":"_shouldClaimTnd",
        "type":"bool"
      },
      {
        "internalType":"bool",
        "name":"_shouldStakeTnd",
        "type":"bool"
      },
      {
        "internalType":"bool",
        "name":"_shouldClaimEsTnd",
        "type":"bool"
      },
      {
        "internalType":"bool",
        "name":"_shouldStakeEsTnd",
        "type":"bool"
      },
      {
        "internalType":"bool",
        "name":"_shouldStakeMultiplierPoints",
        "type":"bool"
      },
      {
        "internalType":"bool",
        "name":"_shouldClaimWeth",
        "type":"bool"
      },
      {
        "internalType":"bool",
        "name":"_shouldConvertWethToEth",
        "type":"bool"
      }
    ],
    "name":"handleRewards",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_weth",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_tnd",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_esTnd",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_bnTnd",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_stakedTndTracker",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_bonusTndTracker",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_feeTndTracker",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_tndVester",
        "type":"address"
      }
    ],
    "name":"initialize",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"isInitialized",
    "outputs":[
      {
        "internalType":"bool",
        "name":"",
        "type":"bool"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "name":"pendingReceivers",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_gov",
        "type":"address"
      }
    ],
    "name":"setGov",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_receiver",
        "type":"address"
      }
    ],
    "name":"signalTransfer",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"_amount",
        "type":"uint256"
      }
    ],
    "name":"stakeEsTnd",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"_amount",
        "type":"uint256"
      }
    ],
    "name":"stakeTnd",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_account",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"_amount",
        "type":"uint256"
      }
    ],
    "name":"stakeTndForAccount",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"stakedTndTracker",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"tnd",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"tndVester",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"_amount",
        "type":"uint256"
      }
    ],
    "name":"unstakeEsTnd",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"uint256",
        "name":"_amount",
        "type":"uint256"
      }
    ],
    "name":"unstakeTnd",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "inputs": [],
    "name":"weth",
    "outputs":[
      {
        "internalType":"address",
        "name":"",
        "type":"address"
      }
    ],
    "stateMutability":"view",
    "type":"function"
  },
  {
    "inputs":[
      {
        "internalType":"address",
        "name":"_token",
        "type":"address"
      },
      {
        "internalType":"address",
        "name":"_account",
        "type":"address"
      },
      {
        "internalType":"uint256",
        "name":"_amount",
        "type":"uint256"
      }
    ],
    "name":"withdrawToken",
    "outputs": [],
    "stateMutability":"nonpayable",
    "type":"function"
  },
  {
    "stateMutability":"payable",
    "type":"receive"
  }
]
